
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Reminders` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Reminders
 * 
 */
export type RemindersModel = runtime.Types.Result.DefaultSelection<Prisma.$RemindersPayload>

export type AggregateReminders = {
  _count: RemindersCountAggregateOutputType | null
  _avg: RemindersAvgAggregateOutputType | null
  _sum: RemindersSumAggregateOutputType | null
  _min: RemindersMinAggregateOutputType | null
  _max: RemindersMaxAggregateOutputType | null
}

export type RemindersAvgAggregateOutputType = {
  id: number | null
  productId: number | null
  userId: number | null
}

export type RemindersSumAggregateOutputType = {
  id: number | null
  productId: number | null
  userId: number | null
}

export type RemindersMinAggregateOutputType = {
  id: number | null
  jobKey: string | null
  createdAt: Date | null
  remindAt: Date | null
  isActive: boolean | null
  productId: number | null
  userId: number | null
}

export type RemindersMaxAggregateOutputType = {
  id: number | null
  jobKey: string | null
  createdAt: Date | null
  remindAt: Date | null
  isActive: boolean | null
  productId: number | null
  userId: number | null
}

export type RemindersCountAggregateOutputType = {
  id: number
  jobKey: number
  createdAt: number
  remindAt: number
  isActive: number
  productId: number
  userId: number
  _all: number
}


export type RemindersAvgAggregateInputType = {
  id?: true
  productId?: true
  userId?: true
}

export type RemindersSumAggregateInputType = {
  id?: true
  productId?: true
  userId?: true
}

export type RemindersMinAggregateInputType = {
  id?: true
  jobKey?: true
  createdAt?: true
  remindAt?: true
  isActive?: true
  productId?: true
  userId?: true
}

export type RemindersMaxAggregateInputType = {
  id?: true
  jobKey?: true
  createdAt?: true
  remindAt?: true
  isActive?: true
  productId?: true
  userId?: true
}

export type RemindersCountAggregateInputType = {
  id?: true
  jobKey?: true
  createdAt?: true
  remindAt?: true
  isActive?: true
  productId?: true
  userId?: true
  _all?: true
}

export type RemindersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Reminders to aggregate.
   */
  where?: Prisma.RemindersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reminders to fetch.
   */
  orderBy?: Prisma.RemindersOrderByWithRelationInput | Prisma.RemindersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RemindersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reminders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reminders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Reminders
  **/
  _count?: true | RemindersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RemindersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RemindersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RemindersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RemindersMaxAggregateInputType
}

export type GetRemindersAggregateType<T extends RemindersAggregateArgs> = {
      [P in keyof T & keyof AggregateReminders]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReminders[P]>
    : Prisma.GetScalarType<T[P], AggregateReminders[P]>
}




export type RemindersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RemindersWhereInput
  orderBy?: Prisma.RemindersOrderByWithAggregationInput | Prisma.RemindersOrderByWithAggregationInput[]
  by: Prisma.RemindersScalarFieldEnum[] | Prisma.RemindersScalarFieldEnum
  having?: Prisma.RemindersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RemindersCountAggregateInputType | true
  _avg?: RemindersAvgAggregateInputType
  _sum?: RemindersSumAggregateInputType
  _min?: RemindersMinAggregateInputType
  _max?: RemindersMaxAggregateInputType
}

export type RemindersGroupByOutputType = {
  id: number
  jobKey: string
  createdAt: Date
  remindAt: Date
  isActive: boolean
  productId: number
  userId: number
  _count: RemindersCountAggregateOutputType | null
  _avg: RemindersAvgAggregateOutputType | null
  _sum: RemindersSumAggregateOutputType | null
  _min: RemindersMinAggregateOutputType | null
  _max: RemindersMaxAggregateOutputType | null
}

type GetRemindersGroupByPayload<T extends RemindersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RemindersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RemindersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RemindersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RemindersGroupByOutputType[P]>
      }
    >
  >



export type RemindersWhereInput = {
  AND?: Prisma.RemindersWhereInput | Prisma.RemindersWhereInput[]
  OR?: Prisma.RemindersWhereInput[]
  NOT?: Prisma.RemindersWhereInput | Prisma.RemindersWhereInput[]
  id?: Prisma.IntFilter<"Reminders"> | number
  jobKey?: Prisma.StringFilter<"Reminders"> | string
  createdAt?: Prisma.DateTimeFilter<"Reminders"> | Date | string
  remindAt?: Prisma.DateTimeFilter<"Reminders"> | Date | string
  isActive?: Prisma.BoolFilter<"Reminders"> | boolean
  productId?: Prisma.IntFilter<"Reminders"> | number
  userId?: Prisma.IntFilter<"Reminders"> | number
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type RemindersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  jobKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  remindAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type RemindersWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  jobKey?: string
  AND?: Prisma.RemindersWhereInput | Prisma.RemindersWhereInput[]
  OR?: Prisma.RemindersWhereInput[]
  NOT?: Prisma.RemindersWhereInput | Prisma.RemindersWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Reminders"> | Date | string
  remindAt?: Prisma.DateTimeFilter<"Reminders"> | Date | string
  isActive?: Prisma.BoolFilter<"Reminders"> | boolean
  productId?: Prisma.IntFilter<"Reminders"> | number
  userId?: Prisma.IntFilter<"Reminders"> | number
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "jobKey">

export type RemindersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  jobKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  remindAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.RemindersCountOrderByAggregateInput
  _avg?: Prisma.RemindersAvgOrderByAggregateInput
  _max?: Prisma.RemindersMaxOrderByAggregateInput
  _min?: Prisma.RemindersMinOrderByAggregateInput
  _sum?: Prisma.RemindersSumOrderByAggregateInput
}

export type RemindersScalarWhereWithAggregatesInput = {
  AND?: Prisma.RemindersScalarWhereWithAggregatesInput | Prisma.RemindersScalarWhereWithAggregatesInput[]
  OR?: Prisma.RemindersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RemindersScalarWhereWithAggregatesInput | Prisma.RemindersScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Reminders"> | number
  jobKey?: Prisma.StringWithAggregatesFilter<"Reminders"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Reminders"> | Date | string
  remindAt?: Prisma.DateTimeWithAggregatesFilter<"Reminders"> | Date | string
  isActive?: Prisma.BoolWithAggregatesFilter<"Reminders"> | boolean
  productId?: Prisma.IntWithAggregatesFilter<"Reminders"> | number
  userId?: Prisma.IntWithAggregatesFilter<"Reminders"> | number
}

export type RemindersCreateInput = {
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  product: Prisma.ProductCreateNestedOneWithoutRemindersInput
  user: Prisma.UserCreateNestedOneWithoutRemindersInput
}

export type RemindersUncheckedCreateInput = {
  id?: number
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  productId: number
  userId: number
}

export type RemindersUpdateInput = {
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  product?: Prisma.ProductUpdateOneRequiredWithoutRemindersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutRemindersNestedInput
}

export type RemindersUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RemindersCreateManyInput = {
  id?: number
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  productId: number
  userId: number
}

export type RemindersUpdateManyMutationInput = {
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type RemindersUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RemindersListRelationFilter = {
  every?: Prisma.RemindersWhereInput
  some?: Prisma.RemindersWhereInput
  none?: Prisma.RemindersWhereInput
}

export type RemindersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RemindersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  jobKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  remindAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type RemindersAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type RemindersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  jobKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  remindAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type RemindersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  jobKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  remindAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type RemindersSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type RemindersCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.RemindersCreateWithoutUserInput, Prisma.RemindersUncheckedCreateWithoutUserInput> | Prisma.RemindersCreateWithoutUserInput[] | Prisma.RemindersUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RemindersCreateOrConnectWithoutUserInput | Prisma.RemindersCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.RemindersCreateManyUserInputEnvelope
  connect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
}

export type RemindersUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.RemindersCreateWithoutUserInput, Prisma.RemindersUncheckedCreateWithoutUserInput> | Prisma.RemindersCreateWithoutUserInput[] | Prisma.RemindersUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RemindersCreateOrConnectWithoutUserInput | Prisma.RemindersCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.RemindersCreateManyUserInputEnvelope
  connect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
}

export type RemindersUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.RemindersCreateWithoutUserInput, Prisma.RemindersUncheckedCreateWithoutUserInput> | Prisma.RemindersCreateWithoutUserInput[] | Prisma.RemindersUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RemindersCreateOrConnectWithoutUserInput | Prisma.RemindersCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.RemindersUpsertWithWhereUniqueWithoutUserInput | Prisma.RemindersUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.RemindersCreateManyUserInputEnvelope
  set?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  disconnect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  delete?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  connect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  update?: Prisma.RemindersUpdateWithWhereUniqueWithoutUserInput | Prisma.RemindersUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.RemindersUpdateManyWithWhereWithoutUserInput | Prisma.RemindersUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.RemindersScalarWhereInput | Prisma.RemindersScalarWhereInput[]
}

export type RemindersUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.RemindersCreateWithoutUserInput, Prisma.RemindersUncheckedCreateWithoutUserInput> | Prisma.RemindersCreateWithoutUserInput[] | Prisma.RemindersUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RemindersCreateOrConnectWithoutUserInput | Prisma.RemindersCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.RemindersUpsertWithWhereUniqueWithoutUserInput | Prisma.RemindersUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.RemindersCreateManyUserInputEnvelope
  set?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  disconnect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  delete?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  connect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  update?: Prisma.RemindersUpdateWithWhereUniqueWithoutUserInput | Prisma.RemindersUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.RemindersUpdateManyWithWhereWithoutUserInput | Prisma.RemindersUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.RemindersScalarWhereInput | Prisma.RemindersScalarWhereInput[]
}

export type RemindersCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.RemindersCreateWithoutProductInput, Prisma.RemindersUncheckedCreateWithoutProductInput> | Prisma.RemindersCreateWithoutProductInput[] | Prisma.RemindersUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.RemindersCreateOrConnectWithoutProductInput | Prisma.RemindersCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.RemindersCreateManyProductInputEnvelope
  connect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
}

export type RemindersUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.RemindersCreateWithoutProductInput, Prisma.RemindersUncheckedCreateWithoutProductInput> | Prisma.RemindersCreateWithoutProductInput[] | Prisma.RemindersUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.RemindersCreateOrConnectWithoutProductInput | Prisma.RemindersCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.RemindersCreateManyProductInputEnvelope
  connect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
}

export type RemindersUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.RemindersCreateWithoutProductInput, Prisma.RemindersUncheckedCreateWithoutProductInput> | Prisma.RemindersCreateWithoutProductInput[] | Prisma.RemindersUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.RemindersCreateOrConnectWithoutProductInput | Prisma.RemindersCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.RemindersUpsertWithWhereUniqueWithoutProductInput | Prisma.RemindersUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.RemindersCreateManyProductInputEnvelope
  set?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  disconnect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  delete?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  connect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  update?: Prisma.RemindersUpdateWithWhereUniqueWithoutProductInput | Prisma.RemindersUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.RemindersUpdateManyWithWhereWithoutProductInput | Prisma.RemindersUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.RemindersScalarWhereInput | Prisma.RemindersScalarWhereInput[]
}

export type RemindersUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.RemindersCreateWithoutProductInput, Prisma.RemindersUncheckedCreateWithoutProductInput> | Prisma.RemindersCreateWithoutProductInput[] | Prisma.RemindersUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.RemindersCreateOrConnectWithoutProductInput | Prisma.RemindersCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.RemindersUpsertWithWhereUniqueWithoutProductInput | Prisma.RemindersUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.RemindersCreateManyProductInputEnvelope
  set?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  disconnect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  delete?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  connect?: Prisma.RemindersWhereUniqueInput | Prisma.RemindersWhereUniqueInput[]
  update?: Prisma.RemindersUpdateWithWhereUniqueWithoutProductInput | Prisma.RemindersUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.RemindersUpdateManyWithWhereWithoutProductInput | Prisma.RemindersUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.RemindersScalarWhereInput | Prisma.RemindersScalarWhereInput[]
}

export type RemindersCreateWithoutUserInput = {
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  product: Prisma.ProductCreateNestedOneWithoutRemindersInput
}

export type RemindersUncheckedCreateWithoutUserInput = {
  id?: number
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  productId: number
}

export type RemindersCreateOrConnectWithoutUserInput = {
  where: Prisma.RemindersWhereUniqueInput
  create: Prisma.XOR<Prisma.RemindersCreateWithoutUserInput, Prisma.RemindersUncheckedCreateWithoutUserInput>
}

export type RemindersCreateManyUserInputEnvelope = {
  data: Prisma.RemindersCreateManyUserInput | Prisma.RemindersCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type RemindersUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.RemindersWhereUniqueInput
  update: Prisma.XOR<Prisma.RemindersUpdateWithoutUserInput, Prisma.RemindersUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.RemindersCreateWithoutUserInput, Prisma.RemindersUncheckedCreateWithoutUserInput>
}

export type RemindersUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.RemindersWhereUniqueInput
  data: Prisma.XOR<Prisma.RemindersUpdateWithoutUserInput, Prisma.RemindersUncheckedUpdateWithoutUserInput>
}

export type RemindersUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.RemindersScalarWhereInput
  data: Prisma.XOR<Prisma.RemindersUpdateManyMutationInput, Prisma.RemindersUncheckedUpdateManyWithoutUserInput>
}

export type RemindersScalarWhereInput = {
  AND?: Prisma.RemindersScalarWhereInput | Prisma.RemindersScalarWhereInput[]
  OR?: Prisma.RemindersScalarWhereInput[]
  NOT?: Prisma.RemindersScalarWhereInput | Prisma.RemindersScalarWhereInput[]
  id?: Prisma.IntFilter<"Reminders"> | number
  jobKey?: Prisma.StringFilter<"Reminders"> | string
  createdAt?: Prisma.DateTimeFilter<"Reminders"> | Date | string
  remindAt?: Prisma.DateTimeFilter<"Reminders"> | Date | string
  isActive?: Prisma.BoolFilter<"Reminders"> | boolean
  productId?: Prisma.IntFilter<"Reminders"> | number
  userId?: Prisma.IntFilter<"Reminders"> | number
}

export type RemindersCreateWithoutProductInput = {
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  user: Prisma.UserCreateNestedOneWithoutRemindersInput
}

export type RemindersUncheckedCreateWithoutProductInput = {
  id?: number
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  userId: number
}

export type RemindersCreateOrConnectWithoutProductInput = {
  where: Prisma.RemindersWhereUniqueInput
  create: Prisma.XOR<Prisma.RemindersCreateWithoutProductInput, Prisma.RemindersUncheckedCreateWithoutProductInput>
}

export type RemindersCreateManyProductInputEnvelope = {
  data: Prisma.RemindersCreateManyProductInput | Prisma.RemindersCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type RemindersUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.RemindersWhereUniqueInput
  update: Prisma.XOR<Prisma.RemindersUpdateWithoutProductInput, Prisma.RemindersUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.RemindersCreateWithoutProductInput, Prisma.RemindersUncheckedCreateWithoutProductInput>
}

export type RemindersUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.RemindersWhereUniqueInput
  data: Prisma.XOR<Prisma.RemindersUpdateWithoutProductInput, Prisma.RemindersUncheckedUpdateWithoutProductInput>
}

export type RemindersUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.RemindersScalarWhereInput
  data: Prisma.XOR<Prisma.RemindersUpdateManyMutationInput, Prisma.RemindersUncheckedUpdateManyWithoutProductInput>
}

export type RemindersCreateManyUserInput = {
  id?: number
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  productId: number
}

export type RemindersUpdateWithoutUserInput = {
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  product?: Prisma.ProductUpdateOneRequiredWithoutRemindersNestedInput
}

export type RemindersUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  productId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RemindersUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  productId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RemindersCreateManyProductInput = {
  id?: number
  jobKey: string
  createdAt?: Date | string
  remindAt: Date | string
  isActive?: boolean
  userId: number
}

export type RemindersUpdateWithoutProductInput = {
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  user?: Prisma.UserUpdateOneRequiredWithoutRemindersNestedInput
}

export type RemindersUncheckedUpdateWithoutProductInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RemindersUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  jobKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  remindAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type RemindersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  jobKey?: boolean
  createdAt?: boolean
  remindAt?: boolean
  isActive?: boolean
  productId?: boolean
  userId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reminders"]>

export type RemindersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  jobKey?: boolean
  createdAt?: boolean
  remindAt?: boolean
  isActive?: boolean
  productId?: boolean
  userId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reminders"]>

export type RemindersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  jobKey?: boolean
  createdAt?: boolean
  remindAt?: boolean
  isActive?: boolean
  productId?: boolean
  userId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reminders"]>

export type RemindersSelectScalar = {
  id?: boolean
  jobKey?: boolean
  createdAt?: boolean
  remindAt?: boolean
  isActive?: boolean
  productId?: boolean
  userId?: boolean
}

export type RemindersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "jobKey" | "createdAt" | "remindAt" | "isActive" | "productId" | "userId", ExtArgs["result"]["reminders"]>
export type RemindersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type RemindersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type RemindersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $RemindersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Reminders"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    jobKey: string
    createdAt: Date
    remindAt: Date
    isActive: boolean
    productId: number
    userId: number
  }, ExtArgs["result"]["reminders"]>
  composites: {}
}

export type RemindersGetPayload<S extends boolean | null | undefined | RemindersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RemindersPayload, S>

export type RemindersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RemindersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RemindersCountAggregateInputType | true
  }

export interface RemindersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Reminders'], meta: { name: 'Reminders' } }
  /**
   * Find zero or one Reminders that matches the filter.
   * @param {RemindersFindUniqueArgs} args - Arguments to find a Reminders
   * @example
   * // Get one Reminders
   * const reminders = await prisma.reminders.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RemindersFindUniqueArgs>(args: Prisma.SelectSubset<T, RemindersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RemindersClient<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Reminders that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RemindersFindUniqueOrThrowArgs} args - Arguments to find a Reminders
   * @example
   * // Get one Reminders
   * const reminders = await prisma.reminders.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RemindersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RemindersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RemindersClient<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reminders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemindersFindFirstArgs} args - Arguments to find a Reminders
   * @example
   * // Get one Reminders
   * const reminders = await prisma.reminders.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RemindersFindFirstArgs>(args?: Prisma.SelectSubset<T, RemindersFindFirstArgs<ExtArgs>>): Prisma.Prisma__RemindersClient<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reminders that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemindersFindFirstOrThrowArgs} args - Arguments to find a Reminders
   * @example
   * // Get one Reminders
   * const reminders = await prisma.reminders.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RemindersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RemindersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RemindersClient<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Reminders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemindersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Reminders
   * const reminders = await prisma.reminders.findMany()
   * 
   * // Get first 10 Reminders
   * const reminders = await prisma.reminders.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const remindersWithIdOnly = await prisma.reminders.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RemindersFindManyArgs>(args?: Prisma.SelectSubset<T, RemindersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Reminders.
   * @param {RemindersCreateArgs} args - Arguments to create a Reminders.
   * @example
   * // Create one Reminders
   * const Reminders = await prisma.reminders.create({
   *   data: {
   *     // ... data to create a Reminders
   *   }
   * })
   * 
   */
  create<T extends RemindersCreateArgs>(args: Prisma.SelectSubset<T, RemindersCreateArgs<ExtArgs>>): Prisma.Prisma__RemindersClient<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Reminders.
   * @param {RemindersCreateManyArgs} args - Arguments to create many Reminders.
   * @example
   * // Create many Reminders
   * const reminders = await prisma.reminders.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RemindersCreateManyArgs>(args?: Prisma.SelectSubset<T, RemindersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Reminders and returns the data saved in the database.
   * @param {RemindersCreateManyAndReturnArgs} args - Arguments to create many Reminders.
   * @example
   * // Create many Reminders
   * const reminders = await prisma.reminders.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Reminders and only return the `id`
   * const remindersWithIdOnly = await prisma.reminders.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RemindersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RemindersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Reminders.
   * @param {RemindersDeleteArgs} args - Arguments to delete one Reminders.
   * @example
   * // Delete one Reminders
   * const Reminders = await prisma.reminders.delete({
   *   where: {
   *     // ... filter to delete one Reminders
   *   }
   * })
   * 
   */
  delete<T extends RemindersDeleteArgs>(args: Prisma.SelectSubset<T, RemindersDeleteArgs<ExtArgs>>): Prisma.Prisma__RemindersClient<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Reminders.
   * @param {RemindersUpdateArgs} args - Arguments to update one Reminders.
   * @example
   * // Update one Reminders
   * const reminders = await prisma.reminders.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RemindersUpdateArgs>(args: Prisma.SelectSubset<T, RemindersUpdateArgs<ExtArgs>>): Prisma.Prisma__RemindersClient<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Reminders.
   * @param {RemindersDeleteManyArgs} args - Arguments to filter Reminders to delete.
   * @example
   * // Delete a few Reminders
   * const { count } = await prisma.reminders.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RemindersDeleteManyArgs>(args?: Prisma.SelectSubset<T, RemindersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reminders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemindersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Reminders
   * const reminders = await prisma.reminders.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RemindersUpdateManyArgs>(args: Prisma.SelectSubset<T, RemindersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reminders and returns the data updated in the database.
   * @param {RemindersUpdateManyAndReturnArgs} args - Arguments to update many Reminders.
   * @example
   * // Update many Reminders
   * const reminders = await prisma.reminders.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Reminders and only return the `id`
   * const remindersWithIdOnly = await prisma.reminders.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RemindersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RemindersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Reminders.
   * @param {RemindersUpsertArgs} args - Arguments to update or create a Reminders.
   * @example
   * // Update or create a Reminders
   * const reminders = await prisma.reminders.upsert({
   *   create: {
   *     // ... data to create a Reminders
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Reminders we want to update
   *   }
   * })
   */
  upsert<T extends RemindersUpsertArgs>(args: Prisma.SelectSubset<T, RemindersUpsertArgs<ExtArgs>>): Prisma.Prisma__RemindersClient<runtime.Types.Result.GetResult<Prisma.$RemindersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Reminders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemindersCountArgs} args - Arguments to filter Reminders to count.
   * @example
   * // Count the number of Reminders
   * const count = await prisma.reminders.count({
   *   where: {
   *     // ... the filter for the Reminders we want to count
   *   }
   * })
  **/
  count<T extends RemindersCountArgs>(
    args?: Prisma.Subset<T, RemindersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RemindersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Reminders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemindersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RemindersAggregateArgs>(args: Prisma.Subset<T, RemindersAggregateArgs>): Prisma.PrismaPromise<GetRemindersAggregateType<T>>

  /**
   * Group by Reminders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemindersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RemindersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RemindersGroupByArgs['orderBy'] }
      : { orderBy?: RemindersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RemindersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRemindersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Reminders model
 */
readonly fields: RemindersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Reminders.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RemindersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Reminders model
 */
export interface RemindersFieldRefs {
  readonly id: Prisma.FieldRef<"Reminders", 'Int'>
  readonly jobKey: Prisma.FieldRef<"Reminders", 'String'>
  readonly createdAt: Prisma.FieldRef<"Reminders", 'DateTime'>
  readonly remindAt: Prisma.FieldRef<"Reminders", 'DateTime'>
  readonly isActive: Prisma.FieldRef<"Reminders", 'Boolean'>
  readonly productId: Prisma.FieldRef<"Reminders", 'Int'>
  readonly userId: Prisma.FieldRef<"Reminders", 'Int'>
}
    

// Custom InputTypes
/**
 * Reminders findUnique
 */
export type RemindersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * Filter, which Reminders to fetch.
   */
  where: Prisma.RemindersWhereUniqueInput
}

/**
 * Reminders findUniqueOrThrow
 */
export type RemindersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * Filter, which Reminders to fetch.
   */
  where: Prisma.RemindersWhereUniqueInput
}

/**
 * Reminders findFirst
 */
export type RemindersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * Filter, which Reminders to fetch.
   */
  where?: Prisma.RemindersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reminders to fetch.
   */
  orderBy?: Prisma.RemindersOrderByWithRelationInput | Prisma.RemindersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Reminders.
   */
  cursor?: Prisma.RemindersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reminders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reminders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Reminders.
   */
  distinct?: Prisma.RemindersScalarFieldEnum | Prisma.RemindersScalarFieldEnum[]
}

/**
 * Reminders findFirstOrThrow
 */
export type RemindersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * Filter, which Reminders to fetch.
   */
  where?: Prisma.RemindersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reminders to fetch.
   */
  orderBy?: Prisma.RemindersOrderByWithRelationInput | Prisma.RemindersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Reminders.
   */
  cursor?: Prisma.RemindersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reminders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reminders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Reminders.
   */
  distinct?: Prisma.RemindersScalarFieldEnum | Prisma.RemindersScalarFieldEnum[]
}

/**
 * Reminders findMany
 */
export type RemindersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * Filter, which Reminders to fetch.
   */
  where?: Prisma.RemindersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reminders to fetch.
   */
  orderBy?: Prisma.RemindersOrderByWithRelationInput | Prisma.RemindersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Reminders.
   */
  cursor?: Prisma.RemindersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reminders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reminders.
   */
  skip?: number
  distinct?: Prisma.RemindersScalarFieldEnum | Prisma.RemindersScalarFieldEnum[]
}

/**
 * Reminders create
 */
export type RemindersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * The data needed to create a Reminders.
   */
  data: Prisma.XOR<Prisma.RemindersCreateInput, Prisma.RemindersUncheckedCreateInput>
}

/**
 * Reminders createMany
 */
export type RemindersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Reminders.
   */
  data: Prisma.RemindersCreateManyInput | Prisma.RemindersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Reminders createManyAndReturn
 */
export type RemindersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * The data used to create many Reminders.
   */
  data: Prisma.RemindersCreateManyInput | Prisma.RemindersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Reminders update
 */
export type RemindersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * The data needed to update a Reminders.
   */
  data: Prisma.XOR<Prisma.RemindersUpdateInput, Prisma.RemindersUncheckedUpdateInput>
  /**
   * Choose, which Reminders to update.
   */
  where: Prisma.RemindersWhereUniqueInput
}

/**
 * Reminders updateMany
 */
export type RemindersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Reminders.
   */
  data: Prisma.XOR<Prisma.RemindersUpdateManyMutationInput, Prisma.RemindersUncheckedUpdateManyInput>
  /**
   * Filter which Reminders to update
   */
  where?: Prisma.RemindersWhereInput
  /**
   * Limit how many Reminders to update.
   */
  limit?: number
}

/**
 * Reminders updateManyAndReturn
 */
export type RemindersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * The data used to update Reminders.
   */
  data: Prisma.XOR<Prisma.RemindersUpdateManyMutationInput, Prisma.RemindersUncheckedUpdateManyInput>
  /**
   * Filter which Reminders to update
   */
  where?: Prisma.RemindersWhereInput
  /**
   * Limit how many Reminders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Reminders upsert
 */
export type RemindersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * The filter to search for the Reminders to update in case it exists.
   */
  where: Prisma.RemindersWhereUniqueInput
  /**
   * In case the Reminders found by the `where` argument doesn't exist, create a new Reminders with this data.
   */
  create: Prisma.XOR<Prisma.RemindersCreateInput, Prisma.RemindersUncheckedCreateInput>
  /**
   * In case the Reminders was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RemindersUpdateInput, Prisma.RemindersUncheckedUpdateInput>
}

/**
 * Reminders delete
 */
export type RemindersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
  /**
   * Filter which Reminders to delete.
   */
  where: Prisma.RemindersWhereUniqueInput
}

/**
 * Reminders deleteMany
 */
export type RemindersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Reminders to delete
   */
  where?: Prisma.RemindersWhereInput
  /**
   * Limit how many Reminders to delete.
   */
  limit?: number
}

/**
 * Reminders without action
 */
export type RemindersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminders
   */
  select?: Prisma.RemindersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminders
   */
  omit?: Prisma.RemindersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemindersInclude<ExtArgs> | null
}
